# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WT386-CFs76ZEXC-H1bU5tfji-5tup2p
"""

A = 25
B = 25
print(A+B)

